const emailLayout = require("./emailLayout");

function poExpiryReminderEmail(record, reminderType) {
    const title =
    reminderType === "2_MONTH"
        ? `PO Expiry Reminder (2 Months) - ${record.po}`
        : `Urgent: PO Expiry Reminder (1 Month) - ${record.po}`;

    const message =
        reminderType === "2_MONTH"
            ? `This is a reminder that the following Purchase Order (PO) is due to expire within the next <strong>2 months</strong>. Kindly initiate the creation of a new PR/PO, if not already initiated, to ensure uninterrupted services.`
            : 
            `This is a reminder that the following Purchase Order (PO) is due to expire within the next <strong>1 month</strong>. If a new PR/PO has not yet been initiated, kindly take the necessary action immediately to avoid service disruption.`;

    const content = `
        <p>Hello,</p>
        <p>${message}</p>

        <table width="100%" cellpadding="10" cellspacing="0" style="border-collapse:collapse;border:1px solid #ddd;">
            <tr style="background:#ff6b00;color:white;">
                <th align="left">Field</th>
                <th align="left">Value</th>
            </tr>

            <tr>
                <td>Vendor Name</td>
                <td>${record.vendorName}</td>
            </tr>

            <tr>
                <td>Vendor Code</td>
                <td>${record.vendorCode}</td>
            </tr>

            <tr>
                <td>Purchase Order (PO)</td>
                <td>${record.po}</td>
            </tr>

            <tr>
                <td>Description</td>
                <td>${record.poDescription}</td>
            </tr>

            <tr>
                <td>PO End Date</td>
                <td>${new Date(record.poEndDate).toLocaleDateString("en-GB")}</td>
            </tr>

            <tr>
                <td>PO Amount</td>
                <td>₹${Number(record.poAmount).toLocaleString("en-IN")}</td>
            </tr>
        </table>
        <br>
        <p>This is an automated reminder generated by the <strong>IT Infra Management System</strong>.</p>
        <br>
        Regards,<br>
        IT Admin
    `;

    return emailLayout(title, content);
}

module.exports = poExpiryReminderEmail;