const emailLayout = require("./emailLayout");

function poExpiryReminderEmail(record, reminderType) {
    const title = reminderType === "2_MONTH" ? "PO Expiry Reminder - 2 Months Remaining" : "Urgent: PO Expiry Reminder - 1 Month Remaining";

    const message =
        reminderType === "2_MONTH"
            ? `This is to inform you that the following Purchase Order (PO) will expire within the next <strong>2 months</strong>. Kindly initiate the renewal process if required.`
            : 
            `This is to inform you that the following Purchase Order (PO) will expire within the next <strong>1 month</strong>. Kindly take the necessary action immediately.`;

    const content = `
        <p>Hello,</p>
        <p>${message}</p>

        <table width="100%" cellpadding="10" cellspacing="0" style="border-collapse:collapse;border:1px solid #ddd;">
            <tr style="background:#ff6b00;color:white;">
                <th align="left">Field</th>
                <th align="left">Value</th>
            </tr>

            <tr>
                <td>Vendor Name</td>
                <td>${record.vendorName}</td>
            </tr>

            <tr>
                <td>Vendor Code</td>
                <td>${record.vendorCode}</td>
            </tr>

            <tr>
                <td>Purchase Order (PO)</td>
                <td>${record.po}</td>
            </tr>

            <tr>
                <td>Description</td>
                <td>${record.poDescription}</td>
            </tr>

            <tr>
                <td>PO End Date</td>
                <td>${new Date(record.poEndDate).toLocaleDateString("en-GB")}</td>
            </tr>

            <tr>
                <td>PO Amount</td>
                <td>₹${Number(record.poAmount).toLocaleString("en-IN")}</td>
            </tr>
        </table>
        <br>
        <p>This is an automated reminder generated by the <strong>IT Infra Management System</strong>.</p>
        <br>
        Regards,<br>
        IT Admin
    `;

    return emailLayout(title, content);
}

module.exports = poExpiryReminderEmail;