name: PO Reminder

on:
  schedule:
    # 10:15 AM IST (04:45 UTC)
    - cron: "45 4 * * *"

    # 11:20 AM IST (4:50 UTC)
    - cron: "50 4 * * *"

  workflow_dispatch:

jobs:
  send-reminders:
    runs-on: ubuntu-latest

    steps:
      - name: Call Reminder API
        run: |
          curl -X GET "${{ secrets.REMINDER_URL }}" \
            -H "Authorization: Bearer ${{ secrets.REMINDER_SECRET }}"